'use strict';
const $=id=>document.getElementById(id);
let stream=null,context=null,analyser=null,buffer=null,raf=null,starting=false,smoothed=0,moodIndex=0,lastTime=0,session=0;
const moods=[{name:'Tranquilo',hint:'Vamos manter assim?',speech:'Shhh… estou de olho.',skin:'#82b952',light:'#b1d879',dark:'#54883b',background:'#e8eddb',accent:'#b7f56d',left:'M176 156 Q203 144 228 156',right:'M272 156 Q297 144 324 156',mouth:'M214 253 Q250 276 286 253'},{name:'Incomodado',hint:'O barulho está aumentando…',speech:'Hmm… dá para falar mais baixo?',skin:'#d9ad4b',light:'#f0d782',dark:'#a17b30',background:'#f1e8cf',accent:'#e6bc5c',left:'M176 151 Q203 151 228 166',right:'M272 166 Q297 151 324 151',mouth:'M218 264 Q250 255 282 264'},{name:'Bravo',hint:'Hora de baixar o volume!',speech:'GRRR! Um pouco de silêncio!',skin:'#da7262',light:'#efaa85',dark:'#a4483d',background:'#f1dcd4',accent:'#ef8172',left:'M176 150 Q203 159 228 177',right:'M272 177 Q297 159 324 150',mouth:'M214 274 Q250 241 286 274'}];
function render(value){const n=Math.max(0,Math.min(100,Math.round(value)));$('level').textContent=n;$('meter').setAttribute('aria-valuenow',n);$('meterFill').style.width=n+'%';let next=moodIndex;if(n>=62)next=2;else if(n>=32 && (moodIndex!==2||n<56))next=1;else if(n<26)next=0;else if(moodIndex===2&&n<56)next=1;if(next!==moodIndex){moodIndex=next;setMood(next);}if(window.trollObjects)window.trollObjects.updateLevel(n,Boolean(stream)||$('demo').checked);}
function setMood(index){if(window.trollObjects)window.trollObjects.setMood(index);const m=moods[index];const root=document.documentElement.style;root.setProperty('--skin',m.skin);root.setProperty('--skin-light',m.light);root.setProperty('--skin-dark',m.dark);root.setProperty('--accent',m.accent);$('stage').style.backgroundColor=m.background;$('stage').classList.toggle('angry',index===2);$('stage').classList.toggle('annoyed',index===1);$('mood').textContent=m.name;$('moodHint').textContent=m.hint;$('speech').textContent=m.speech;$('browLeft').setAttribute('d',m.left);$('browRight').setAttribute('d',m.right);$('mouth').setAttribute('d',m.mouth);$('anger').setAttribute('opacity',index===2?'1':'0');if(!window.trollObjects)$('troll').setAttribute('aria-label','Troll '+m.name.toLowerCase());for(let i=0;i<3;i++)$('state'+i).classList.toggle('selected',i===index);if(index>0&&window.trollObjects)window.trollObjects.shush();}
function stop(){session++;if(raf)cancelAnimationFrame(raf);raf=null;if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;if(context){context.close().catch(()=>{});context=null;}analyser=null;starting=false;$('start').disabled=false;$('start').innerHTML='Ativar microfone <span>↗</span>';$('live').textContent='PAUSADO';$('sourceLabel').textContent='● AGUARDANDO MICROFONE';smoothed=0;render(0);}
function measure(time){if(!analyser)return;analyser.getFloatTimeDomainData(buffer);let sum=0;for(const v of buffer)sum+=v*v;const rms=Math.sqrt(sum/buffer.length);const gain=[0,0.55,0.8,1.15,1.7,2.6][Number($('sensitivity').value)];const relative=Math.min(100,Math.max(0,(20*Math.log10(Math.max(rms*gain,0.00001))+65)/50*100));const dt=Math.min((time-lastTime)/1000,.1)||.016;lastTime=time;smoothed+=(relative-smoothed)*(1-Math.exp(-dt/(relative>smoothed?.16:.65)));render(smoothed);raf=requestAnimationFrame(measure);}
$('start').addEventListener('click',async()=>{if(stream){stop();$('notice').textContent='Microfone desligado. O troll está descansando.';return;}if(starting)return;$('demo').checked=false;$('demoRange').hidden=true;if(!navigator.mediaDevices?.getUserMedia){$('notice').textContent='Microfone indisponível. Abra em HTTPS em um navegador compatível ou use a demonstração.';return;}starting=true;const current=++session;$('start').disabled=true;$('notice').textContent='Aguardando sua permissão para acessar o microfone…';let acquired=null;try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)throw new Error('AudioContext indisponível');context=new AudioCtx();await context.resume();acquired=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});if(current!==session){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;analyser=context.createAnalyser();analyser.fftSize=2048;buffer=new Float32Array(analyser.fftSize);context.createMediaStreamSource(stream).connect(analyser);$('start').innerHTML='Desligar microfone <span>■</span>';$('sourceLabel').textContent='● OUVINDO O AMBIENTE';$('live').textContent='AO VIVO';$('notice').textContent='Microfone ativo. Ajuste a sensibilidade para a sua sala.';lastTime=performance.now();raf=requestAnimationFrame(measure);}catch(error){if(current!==session)return;if(acquired)acquired.getTracks().forEach(t=>t.stop());stop();$('notice').textContent=error.name==='NotAllowedError'?'Permissão negada. Libere o microfone nas configurações do navegador ou use a demonstração.':error.name==='NotFoundError'?'Nenhum microfone encontrado. Você pode usar a demonstração.':'Não foi possível iniciar o microfone. Feche outros aplicativos que o utilizem e tente novamente.';}finally{if(current===session){starting=false;$('start').disabled=false;}}});
$('sensitivity').addEventListener('input',()=>{$('sensitivityText').textContent=['Baixa','Moderada','Média','Alta','Muito alta'][Number($('sensitivity').value)-1];});
$('demo').addEventListener('change',()=>{stop();const enabled=$('demo').checked;$('demoRange').hidden=!enabled;if(enabled){$('live').textContent='SIMULAÇÃO';$('sourceLabel').textContent='● MODO DEMONSTRAÇÃO';$('notice').textContent='Arraste o controle abaixo e veja o troll mudar de humor.';render(Number($('demoLevel').value));}else $('notice').textContent='Permita o microfone para o troll ouvir a sala.';});
$('demoLevel').addEventListener('input',()=>{if($('demo').checked)render(Number($('demoLevel').value));});
window.addEventListener('pagehide',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden&&(stream||starting)){stop();$('notice').textContent='Microfone pausado ao sair da página. Ative novamente para continuar.';}});setMood(0);
