'use strict';
(()=>{
const $=id=>document.getElementById(id);
const colors=['#a6d668','#e6bc5c','#ef8172'],names=['Tranquilo','Irritado','Bravo'];
function face(index){const brows=index===0?'M19 27Q27 23 34 27 M46 27Q53 23 61 27':index===1?'M19 24L34 30 M46 30L61 24':'M19 22L34 32 M46 32L61 22';const mouth=index===0?'M28 51Q40 63 52 51':index===1?'M29 56Q40 51 51 56':'M28 58Q40 44 52 58';return `<svg viewBox="0 0 80 80" aria-hidden="true"><path d="M18 30L4 19L8 43L18 45 M62 30L76 19L72 43L62 45" fill="${colors[index]}" stroke="#344434" stroke-width="2"/><path d="M23 17L20 5L33 14 M47 14L60 5L57 17" fill="#f2dfb1" stroke="#344434" stroke-width="2"/><rect x="15" y="14" width="50" height="54" rx="21" fill="${colors[index]}" stroke="#344434" stroke-width="2"/><ellipse cx="28" cy="37" rx="8" ry="9" fill="#fff7df"/><ellipse cx="52" cy="37" rx="8" ry="9" fill="#fff7df"/><circle cx="30" cy="39" r="3" fill="#344434"/><circle cx="50" cy="39" r="3" fill="#344434"/><path d="${brows}" stroke="#344434" stroke-width="4" fill="none" stroke-linecap="round"/><path d="${mouth}" stroke="#344434" stroke-width="3" fill="none" stroke-linecap="round"/></svg>`;}
$('timeCards').innerHTML=names.map((name,i)=>`<div class="time-card" id="timeCard${i}"><div class="mini-face">${face(i)}</div><div class="time-data"><div class="time-label"><strong>${name}</strong><span id="percent${i}">0,0%</span></div><div class="time-bar" role="meter" aria-label="Porcentagem do tempo ${name.toLowerCase()}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" id="timeMeter${i}"><div id="timeFill${i}" style="background:${colors[i]}"></div></div><small id="duration${i}">00:00</small></div></div>`).join('');
const sessions={microphone:[0,0,0],demo:[0,0,0]};let mode='microphone',active=false,mood=0,last=performance.now(),audioContext=null,lastShush=-Infinity,soundUntil=0,sources=[];
function flush(){const now=performance.now();if(active)sessions[mode][mood]+=Math.max(0,now-last);last=now;}
function formatTime(ms){const s=Math.floor(ms/1000);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function paint(){const times=sessions[mode],total=times.reduce((a,b)=>a+b,0),raw=times.map(t=>total?t/total*1000:0),parts=raw.map(Math.floor);if(total){const missing=1000-parts.reduce((a,b)=>a+b,0),order=[0,1,2].sort((a,b)=>(raw[b]-parts[b])-(raw[a]-parts[a]));for(let j=0;j<missing;j++)parts[order[j]]++;}for(let i=0;i<3;i++){const percent=parts[i]/10;$('percent'+i).textContent=percent.toFixed(1).replace('.',',')+'%';$('timeFill'+i).style.width=percent+'%';$('timeMeter'+i).setAttribute('aria-valuenow',percent);$('duration'+i).textContent=formatTime(times[i]);$('timeCard'+i).classList.toggle('current',active&&i===mood);}$('totalTime').textContent=formatTime(total);$('statsStatus').textContent=active?(mode==='demo'?'Demonstração • contagem em tempo real':'Microfone ativo • contagem em tempo real'):(total?'Contagem pausada. Retome para continuar.':'Ative o microfone ou a demonstração.');}
function update(running,nextMood,nextMode=mode){flush();mode=nextMode;active=running&&!document.hidden;mood=nextMood;paint();}
function stopAudio(){for(const source of sources){try{source.stop();}catch{}}sources=[];soundUntil=0;}
async function unlockSound(){try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx){$('soundNotice').textContent='Áudio indisponível neste navegador.';return false;}audioContext??=new AudioCtx();if(audioContext.state==='suspended')await audioContext.resume();return audioContext.state==='running';}catch{$('soundNotice').textContent='Não foi possível liberar o som. Clique em Testar som para tentar novamente.';return false;}}
async function shushSound(force=false){if(!$('soundEnabled').checked)return;const now=performance.now();if(!force&&now-lastShush<15000)return;if(!audioContext||audioContext.state!=='running'){ $('soundNotice').textContent='Clique em Testar som para liberar o aviso sonoro.';return;}lastShush=now;stopAudio();const ctx=audioContext,t=ctx.currentTime,duration=1.9;
// Ruído filtrado para o “SH” e ressonâncias de vogal para prolongar o “IIII”.
const buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.65;
const noise=ctx.createBufferSource();noise.buffer=buffer;const high=ctx.createBiquadFilter();high.type='highpass';high.frequency.value=1800;const low=ctx.createBiquadFilter();low.type='lowpass';low.frequency.value=7600;const hiss=ctx.createGain();hiss.gain.setValueAtTime(0,t);hiss.gain.linearRampToValueAtTime(.3,t+.08);hiss.gain.linearRampToValueAtTime(.07,t+.5);hiss.gain.linearRampToValueAtTime(.07,t+1.55);hiss.gain.linearRampToValueAtTime(0,t+duration);noise.connect(high).connect(low).connect(hiss).connect(ctx.destination);noise.start(t);noise.stop(t+duration);sources.push(noise);
const voice=ctx.createOscillator();voice.type='sawtooth';voice.frequency.setValueAtTime(175,t);voice.frequency.linearRampToValueAtTime(155,t+duration);for(const [frequency,volume] of [[300,.012],[2400,.009],[3100,.006]]){const formant=ctx.createBiquadFilter();formant.type='bandpass';formant.frequency.value=frequency;formant.Q.value=9;const gain=ctx.createGain();gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(volume,t+.45);gain.gain.linearRampToValueAtTime(volume*.75,t+1.55);gain.gain.linearRampToValueAtTime(0,t+duration);voice.connect(formant).connect(gain).connect(ctx.destination);}voice.start(t);voice.stop(t+duration);sources.push(voice);soundUntil=now+(duration+.65)*1000;$('soundNotice').textContent='SHIIIIIIII! Próximo aviso automático após 15 segundos.';}
window.trollSession={update,unlockSound,shushSound,isSoundPlaying:()=>performance.now()<soundUntil,soundLevel(rms,sensitivity){const gain=.025*Math.pow(160,Math.max(0,Math.min(99,sensitivity-1))/99);return Math.max(0,Math.min(100,(20*Math.log10(Math.max(rms*gain,.000001))+60)/48*100));},snapshot(){flush();return {mode,active,mood,times:[...sessions[mode]]};}};
$('testSound').addEventListener('click',async()=>{if(await unlockSound())await shushSound(true);});$('soundEnabled').addEventListener('change',()=>{if(!$('soundEnabled').checked){stopAudio();$('soundNotice').textContent='Som desligado. O gesto continua funcionando.';}else{unlockSound();$('soundNotice').textContent='Aviso sonoro ativado. Intervalo de 15 segundos.';}});$('resetStats').addEventListener('click',()=>{flush();sessions[mode]=[0,0,0];paint();});
setInterval(()=>{flush();if(document.hidden)active=false;else if($('demo').checked){mode='demo';active=true;}paint();},250);
document.addEventListener('visibilitychange',()=>{flush();if(document.hidden){active=false;stopAudio();}paint();});window.addEventListener('pagehide',()=>{flush();active=false;stopAudio();});paint();
})();
